//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyImage
    {
        public long ID { get; set; }
        public Nullable<long> SurveyID { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public string OriginalImageName { get; set; }
        public string ImageName { get; set; }
        public string ModifiedImageName { get; set; }
        public string Finding { get; set; }
        public string Recommentation { get; set; }
        public Nullable<bool> CanMitieRepair { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual CustomerLocation CustomerLocation { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
