//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.SurveyImages = new HashSet<SurveyImage>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public Nullable<System.TimeSpan> SurveyTime { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public Nullable<long> PilotID { get; set; }
        public Nullable<int> DroneID { get; set; }
        public Nullable<int> SurveyStatusID { get; set; }
        public string EC_ATC { get; set; }
        public string EC_LocalPolice { get; set; }
        public string EC_FireBrigde { get; set; }
        public string EC_AE { get; set; }
        public string WC_Wind { get; set; }
        public string WC_Precipitation { get; set; }
        public string WC_Visibility { get; set; }
        public string WC_CloudCover { get; set; }
        public string WC_KP { get; set; }
        public string W_SunRise { get; set; }
        public string W_SunSet { get; set; }
        public string W_CTAFS { get; set; }
        public string W_WindSpeed { get; set; }
        public string W_Prepreciption { get; set; }
        public string W_Temperature { get; set; }
        public string W_Notams { get; set; }
        public string SH_NotedStructure { get; set; }
        public string SH_PedestrainRisk { get; set; }
        public string SH_VehileRisk { get; set; }
        public string SH_ATR { get; set; }
        public string SH_ExplosiveRisk { get; set; }
        public string MS_Name { get; set; }
        public string MS_Telephone { get; set; }
        public string MS_Email { get; set; }
        public Nullable<System.DateTime> FT_StartTime { get; set; }
        public Nullable<System.DateTime> FT_EndTime { get; set; }
        public Nullable<System.DateTime> TimeHack { get; set; }
        public string NearAreaPopulation { get; set; }
        public string SiteAddress { get; set; }
        public string OperatingArea { get; set; }
        public string Question { get; set; }
        public string WorkDescription { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual SurveyStatu SurveyStatu { get; set; }
        public virtual ICollection<SurveyImage> SurveyImages { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
    }
}
