//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.CustomerLocations = new HashSet<CustomerLocation>();
            this.Surveys = new HashSet<Survey>();
            this.Surveys1 = new HashSet<Survey>();
            this.Surveys2 = new HashSet<Survey>();
            this.AssignedCustomers = new HashSet<AssignedCustomer>();
        }
    
        public long UserId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<CustomerLocation> CustomerLocations { get; set; }
        public virtual ICollection<Survey> Surveys { get; set; }
        public virtual ICollection<Survey> Surveys1 { get; set; }
        public virtual ICollection<Survey> Surveys2 { get; set; }
        public virtual AssignedCustomer AssignedCustomer { get; set; }
        public virtual ICollection<AssignedCustomer> AssignedCustomers { get; set; }
    }
}
